name: Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt install libpcap-dev
      - run: cargo test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install WinPcap
        run: |
          Invoke-WebRequest -Uri "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip" -OutFile "$Env:TEMP\WpdPack.zip"
          Expand-Archive -Path "$Env:TEMP\WpdPack.zip" -DestinationPath "$Env:TEMP"
          New-Item -ItemType Directory -Force -Path "${env:GITHUB_WORKSPACE}\lib"
          Copy-Item -Path "$Env:TEMP\WpdPack\Lib\*" -Destination "${env:GITHUB_WORKSPACE}\lib" -Recurse
        shell: pwsh
      - run: cargo test
